#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Mon Jan 09 12:03:45 IST 2017
apiSecret=214c117b9b1a560cdf56cb085ae5ad3ee9d8d4edaad58476ac3060b270d3e0af
